version: '2'
services:
  nginx:
    image: underser/magento2_nginx
    container_name: <project>_nginx
    ports:
      - "80:8000" # web
      - "443:8443"
    volumes: &appvolumes
      - ./src/app/code:/var/www/html/app/code:delegated
      - ./src/app/design:/var/www/html/app/design:delegated
      - ./src/app/etc:/var/www/html/app/etc:delegated
      - ~/.composer:/var/www/.composer:delegated
      - ~/.npm:/var/www/.npm
      - <project>_appfilesystem:/var/www/html
      - <project>_sockdata:/sock
    depends_on:
      - db
    links:
      - db
      - phpfpm
    networks:
      - <project>-network

  phpfpm:
    image: underser/magento2_php-fpm
    container_name: <project>_phpfpm
    volumes: *appvolumes
    links:
      - db
    networks:
      - <project>-network

  db:
    image: mariadb:10.4
    container_name: <project>_db
    ports:
     - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=magento
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
      - ./src:/home
    networks:
      - <project>-network

  redis:
    image: redis
    container_name: <project>_redis
    ports:
     - 6379
    networks:
      - <project>-network

  redis-session:
    image: redis
    container_name: <project>_redis-session
    ports:
     - 6379
    networks:
      - <project>-network

  mailcatcher:
    container_name: <project>_mailcatcher
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - <project>-network

  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: <project>_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - "discovery.type=single-node"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - <project>-network

networks:
  <project>-network:
    driver: bridge

volumes:
  <project>_appfilesystem:
  dbdata:
    driver: local
  <project>_sockdata:
