#!/bin/bash

read -p "Project name ? " project
read -p "Link to your project git repo ? " repo

sed -i '' -e "s/<project>/$project/g" ./config/docker-compose.yml
sed -i '' -e "s/<project>/$project/g" ./config/env.php

cd src
if [ $repo ]; then
    git clone $repo .
elif [ ! -e ./index.php ]; then
    echo "<?php phpinfo();" > ./index.php;
fi
